//! Boot-time autostart via the per-user Windows registry **Run** key — NO admin.
//!
//! `digse startup add` writes:
//! 1. a hidden-launch shim `<state_dir>/digse-autostart.vbs` that runs
//!    `"<exe>" __start_foreground__ --host <h> --port <p>` with window style 0
//!    (hidden) via `WScript.Shell.Run` — this avoids a console window flashing
//!    at every logon, the standard no-admin hidden-startup trick;
//! 2. the Run value `digse` = `wscript.exe "<shim>"`.
//!
//! Everything lands under `HKCU` (per-user), so there is no UAC prompt and no
//! administrator privilege required — unlike a Windows Service. `remove` deletes
//! both the registry value and the shim.

use winreg::enums::*;
use winreg::RegKey;

use crate::pidfile;

/// `HKCU\Software\Microsoft\Windows\CurrentVersion\Run` — the standard per-user
/// autostart key, processed by Explorer at logon. Per-user ⇒ no UAC/admin.
const RUN_KEY_PATH: &str = r"Software\Microsoft\Windows\CurrentVersion\Run";
const VALUE_NAME: &str = "digse";
const SHIM_NAME: &str = "digse-autostart.vbs";
const ENV_NAME: &str = "autostart.env"; // records host/port for `status`

/// `digse startup status` — report whether the Run value + shim are present.
pub fn status() -> Result<(), Box<dyn std::error::Error>> {
    println!("startup: autostart via HKCU registry Run key (no admin needed)");

    let hkcu = RegKey::predef(HKEY_CURRENT_USER);
    let present = hkcu
        .open_subkey(RUN_KEY_PATH)
        .and_then(|run| run.get_value::<String, _>(VALUE_NAME).map(|_| ()))
        .is_ok();
    println!(
        "registry value: HKCU\\{}\\{} ({})",
        RUN_KEY_PATH,
        VALUE_NAME,
        if present { "present" } else { "absent" }
    );

    let shim = pidfile::state_dir()?.join(SHIM_NAME);
    println!(
        "vbs shim:       {} ({})",
        shim.display(),
        if shim.exists() { "present" } else { "absent" }
    );

    match std::fs::read_to_string(pidfile::state_dir()?.join(ENV_NAME)) {
        Ok(env) => print!("host/port:      {}", env),
        Err(_) => println!("host/port:      (none recorded)"),
    }
    Ok(())
}

/// `digse startup add` — write the VBS shim, record host/port, set the Run value.
/// Does NOT start the daemon now (the user runs `digse start` to avoid a port
/// clash, mirroring the Linux/systemd behavior).
pub fn add() -> Result<(), Box<dyn std::error::Error>> {
    let exe = std::env::current_exe()?;
    let cfg = digse::DigseConfig::load().unwrap_or_default();
    let host = cfg.serve.host.clone();
    let port = cfg.serve.port;

    let state = pidfile::state_dir()?;
    std::fs::create_dir_all(&state)?;

    // 1. Hidden-launch VBS shim. `WScript.Shell.Run(cmd, 0, False)` hides the
    //    window (intWindowStyle=0) and does not wait, so no console flashes at
    //    every logon. The exe path is quoted so spaces are handled.
    let shim = state.join(SHIM_NAME);
    let vbs = format!(
"' digse autostart launcher - generated by `digse startup add`
' Runs the daemon hidden (window style 0); no console flashes at logon.
Set sh = CreateObject(\"WScript.Shell\")
sh.Run \"\"\"{exe}\"\" __start_foreground__ --host {host} --port {port}, 0, False
",
        exe = exe.display().to_string(),
        host = host,
        port = port,
    );
    std::fs::write(&shim, vbs)?;
    println!("startup: wrote {}", shim.display());

    // 2. Record host/port so `status` can show them (the registry value holds
    //    the launcher command, not the config).
    std::fs::write(state.join(ENV_NAME), format!("host={}\nport={}\n", host, port))?;

    // 3. Set the per-user Run value: wscript.exe "<shim>".
    let hkcu = RegKey::predef(HKEY_CURRENT_USER);
    let run = hkcu.open_subkey_with_flags(RUN_KEY_PATH, KEY_SET_VALUE)?;
    let cmd = format!("wscript.exe \"{}\"", shim.display());
    run.set_value(VALUE_NAME, &cmd)?;
    println!("startup: set HKCU\\{}\\{} = {}", RUN_KEY_PATH, VALUE_NAME, cmd);

    println!();
    println!("Autostart is configured; digse will launch at your next login.");
    println!("To start it now:  digse start");
    Ok(())
}

/// `digse startup remove` — delete the Run value and the shim. Idempotent.
pub fn remove() -> Result<(), Box<dyn std::error::Error>> {
    let shim = pidfile::state_dir()?.join(SHIM_NAME);

    let hkcu = RegKey::predef(HKEY_CURRENT_USER);
    let removed_value = match hkcu.open_subkey_with_flags(RUN_KEY_PATH, KEY_SET_VALUE) {
        Ok(run) => match run.delete_value(VALUE_NAME) {
            Ok(()) => true,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => false,
            Err(e) => return Err(e.into()),
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => false,
        Err(e) => return Err(e.into()),
    };
    println!(
        "startup: {} HKCU\\{}\\{}",
        if removed_value {
            "removed"
        } else {
            "no Run value present, left"
        },
        RUN_KEY_PATH,
        VALUE_NAME
    );

    if shim.exists() {
        std::fs::remove_file(&shim)?;
        println!("startup: removed {}", shim.display());
    }
    let _ = std::fs::remove_file(pidfile::state_dir()?.join(ENV_NAME));
    println!("startup: autostart disabled");
    Ok(())
}
